FROM eclipse-temurin:17-alpine
MAINTAINER BingChunMoLi <bingchunmoli@bingchunmoli.com>
RUN mkdir -p /var/log/moliapi
RUN chmod -R a+w /var/log/moliapi
RUN addgroup api && adduser api -D -S -s /bin/bash -G api
RUN chown -R api:api /var/log/moliapi
USER api:api
VOLUME /soft/config
VOLUME /var/log/moliapi
WORKDIR /soft
EXPOSE 8090
ARG JAR_FILE=target/*.jar
ADD ${JAR_FILE} /soft/moliapi.jar
ENV JAVA_OPTS=""
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -Djava.security.egd=file:/dev/urandom -Dspring.config.additional-location=optional:file:/soft/config/ -jar /soft/moliapi.jar ${0} ${@}"]
