version: "3.8"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api
    volumes:
      - ~/.api/mysql/data/:/var/lib/mysql
      - ~/.api/mysql/log/:/var/log/mysql
      - ~/.api/init/db/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/.api/redis/conf/:/etc/redis/
  moliapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: api
    command:
      - --spring.datasource.url=jdbc:mysql://mysql:3306/api?serverTimezone=UTC&allowMultiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
      - --spring.datasource.username=root
      - --spring.datasource.password=password
      - --spring.datasource.password=password
    ports:
      - "8090:8090"
    volumes:
      - ~/.api/:/soft/config/
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
