/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        ElAlert: typeof import('element-plus/es')['ElAlert']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElForm: typeof import('element-plus/es')['ElForm']
        ElFormItem: typeof import('element-plus/es')['ElFormItem']
        ElInput: typeof import('element-plus/es')['ElInput']
        IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
        IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
        IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
        IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
        IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}
