#INIT=runscript from 'classpath:db/h2.sql'
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.api/api.db;MODE=MySQL;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;database_to_upper=false;CASE_INSENSITIVE_IDENTIFIERS=true;
    username: root
    password: root
  mail:
    enable: false
    host:
    port: 465
    username:
    password:
    default-encoding: UTF-8
    protocol: smtps
    defaultTo:
  data:
    redis:
      password:
      port: 6379
      host: localhost
      database: 1
management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: '*'
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED

moli:
  apiConfig:
    weatherKey:
    weatherUri:
    weatherGeoUri:
    serverSauceKey:
    pcPath: ${moli.path}img/mobile/
    mobilePath: ${moli.path}img/pc/
    path1080: ${moli.path}img/1080/
    uploadTempPath: ${moli.path}upload/
    uploadTempSecret: 123456 #一定要修改的上传密码
    certificatePath: #证书路径
    privateKeyPath: #私钥路径
    domain: #更新的域名
logging:
  level:
    com.bingchunmoli: info
    com.baomidou.example.mapper: info
