moli:
  version: @version@
  path: ${user.home}${file.separator}.api${file.separator}
  init:
    sqlPath: ${moli.path}/init/db
    yiYanJsonPath: ${moli.path}/init/data/
  apiConfig:
    weatherKey: #开发版和风天气的key(商业版需要更换weatherUri和weatherGeoUri到商业版域名)
    weatherUri: devapi.qweather.com
    weatherGeoUri: geoapi.qweather.com
    serverSauceKey: #server酱通知的key
    pcPath: ${moli.path}img/pc #pc随机图的图片路径
    mobilePath: ${moli.path}img/mobile #mobile随机图的图片路径
    path1080: ${moli.path}img/1080 #1080接口随机图的图片路径
    uploadTempPath:
    uploadTempSecret:
    certificatePath: #证书路径
    privateKeyPath: #私钥路径
    domain: #更新的域名
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/api?serverTimezone=UTC&allowMultiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      pool-name: moliApi
  data:
    redis:
      database: 1
      connect-timeout: 3000
      timeout: 3000
      password:
      port: 6379
      host: redis

