apiVersion: v1
kind: ConfigMap
metadata:
    name: moliapi-prometheus-config
data:
    prometheus.yml: |
        global:
            scrape_interval: 15s
            evaluation_interval: 15s
        scrape_configs:
            - job_name: prometheus
              static_configs:
                  - targets:
                        - localhost:9090
            - job_name: moliapi
              metrics_path: /actuator/prometheus
              static_configs:
                  - targets:
                        - moliapi:8090