changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - bingchunmoli
  categories:
    - title: Exciting New Features 🎉
      labels:
        - feat
        - feature
        - enhancement
    - title: Other Changes
      labels:
        - "*"
